# General information
baseURL = "https://AnonymerNiklasistanonym.github.io/ShallowDiveBlog/"
title = "Shallow Dive Blog"
defaultContentLanguage = "en-us"

# Enable emojis globally
enableEmoji = true

[params]
  # This defines how dates are formatted (ISO YYYY-MM-DD)
  dateFormat = "2006-01-02"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  showTags = true
  showCategories = true

# Theme
theme = "github.com/hugo-sid/hugo-blog-awesome"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[markup]
  [markup.highlight]
    # Enable code syntax highlighting
    noClasses = false   # Use CSS classes for styling instead of inline styles
    guessSyntax = true  # Guess language if not specified
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true    # Allow raw HTML in Markdown
  [markup.tableOfContents]
    startLevel = 2     # ToC starts from H2
    endLevel = 4       # ToC ends at H4
    ordered = false    # Use <ul> instead of <ol>

############################## All languages ################################
[params.author]
  avatar = "avatar.png" # in assets folder
  intro = "Shallow Dive Blog"
  name = "AnonymerNiklasistanonym"

############################## English language ################################
[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/en"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="search"
    name = 'Search'
    url = '/search/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 30
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 40

[Languages.en-us.params.author]
  description = "Shallow dives into topics I'm interested in."

############################## German language ################################
[Languages.de-de]
  languageName = "English"
  languageCode = "de-de"
  contentDir = "content/de"
  weight = 1

  [Languages.de-de.menu]
  [[Languages.de-de.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[Languages.de-de.menu.main]]
    pageRef="search"
    name = 'Suche'
    url = '/search/'
    weight = 20
  [[Languages.de-de.menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 30
  [[Languages.de-de.menu.main]]
    pageRef="about"
    name = 'Über'
    url = '/about/'
    weight = 40

[Languages.de-de.params.author]
  description = "Oberflächliche Exkurse in Themen, die mich interessieren."

###################################################################

[[params.socialIcons]]
name = "github"
url = "https://github.com/AnonymerNiklasistanonym"

[[params.socialIcons]]
name = "Rss"
url = "./index.xml"
