@startuml
participant Client as C
participant Server as S

box "TCP Handshake"
C -> S: SYN\nSeq=0 Win=65495\nLen=0 MSS=65495\nSACK_PERM TSval=3192259273 WS=128
S --> C: SYN, ACK\nSeq=0 Ack=1\nWin=65483 MSS=65495\nSACK_PERM TSval=3192259273 WS=128
C -> S: ACK\nSeq=1 Ack=1\nWin=65536
end box

C -> S: PSH, ACK\nSeq=1 Ack=1\nLen=14 (Data payload)
S --> C: ACK\nSeq=1 Ack=15\nWin=65536
S --> C: FIN, ACK\nSeq=1 Ack=15\nWin=65536
C -> S: ACK\nSeq=15 Ack=2\nWin=65536
box "Connection Close"
C -> S: FIN, ACK\nSeq=15 Ack=2\nWin=65536
S --> C: ACK\nSeq=2 Ack=16\nWin=65536
end box
@enduml
